#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kicausse <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/07 21:16:44 by kicausse          #+#    #+#              #
#    Updated: 2018/07/07 21:16:45 by kicausse         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = doop

all: $(NAME)

$(NAME):
		gcc -Wall -Werror -Wextra *.c -o ft_advanced_do-op

clean:
	/bin/rm -f ft_advanced_do-op

re: clean all